# Generated by Django 2.2 on 2020-01-27 19:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cozyfolio_app', '0003_auto_20200126_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('title', models.CharField(max_length=100, null=True)),
                ('portfolioSummary', models.TextField(null=True)),
                ('resume', models.FileField(null=True, upload_to='uploads/')),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='cozyfolio_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('summary', models.TextField(null=True)),
                ('techUsed', models.TextField(null=True)),
                ('team', models.TextField(null=True)),
                ('process', models.TextField(null=True)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('updated_at', models.DateField(auto_now=True)),
                ('portfolio', models.ManyToManyField(related_name='project', to='cozyfolio_app.Portfolio')),
            ],
        ),
    ]
