# Generated by Django 2.2 on 2020-01-28 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cozyfolio_app', '0005_auto_20200127_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
    ]
