# Generated by Django 2.2 on 2020-01-28 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cozyfolio_app', '0008_skill_clouds'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='portfolio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cozyfolio_app.Portfolio'),
        ),
        migrations.AddField(
            model_name='skill',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cozyfolio_app.Project'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cozyfolio_app.User'),
        ),
    ]
