# Generated by Django 2.2 on 2020-01-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozyfolio_app', '0009_auto_20200128_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='resume',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='logo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='headshot',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
