# Generated by Django 2.2 on 2020-01-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozyfolio_app', '0012_pdffile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='picImage',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
