# Generated by Django 2.2 on 2020-01-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozyfolio_app', '0013_project_picimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tagLine',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
