# Generated by Django 2.2 on 2020-01-30 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cozyfolio_app', '0014_user_tagline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tagLine',
        ),
    ]
