# Generated by Django 2.2 on 2020-01-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozyfolio_app', '0016_user_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tagLine',
            field=models.CharField(max_length=150),
        ),
    ]
