# Generated by Django 2.2 on 2020-01-30 23:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cozyfolio_app', '0018_auto_20200130_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(null=True, upload_to='settmedia/'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=75)),
                ('company', models.CharField(max_length=75)),
                ('applyDate', models.DateField()),
                ('respondDate', models.DateField()),
                ('response', models.IntegerField()),
                ('estSalary', models.IntegerField()),
                ('numbofJobApplied', models.IntegerField(null=True)),
                ('averageRespond', models.IntegerField(null=True)),
                ('offerReceived', models.IntegerField(null=True)),
                ('offerReject', models.IntegerField(null=True)),
                ('mostPopularPortfolio', models.CharField(max_length=75, null=True)),
                ('numbofCompanyApplied', models.IntegerField(null=True)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('updated_at', models.DateField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='cozyfolio_app.Portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='cozyfolio_app.User')),
            ],
        ),
    ]
